[package]
name = "rdpdk"
version = "0.1.0"
edition = "2024"

[build]
rustflags = ["-Ctarget-feature=+crt-static"]

[lib]
path = "rdpdk.rs"

[workspace]
members = [
    ".",
]

[dependencies]

[[example]]
name = "echo"
crate-type = ["bin"]

[[bin]]
name = "echo"
path = "examples/echo.rs"

