[package]
name = "runpmd"
version = "0.1.0"
edition = "2024"

[build]
rustflags = ["-Ctarget-feature=+crt-static"]

[[bin]]
name = "runpmd"
path = "runpmd.rs"

[dependencies]
rdpdk = {path = "../.."}


